language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
python:
  - "3.8"
script:
  - set -e
  - pip install aibolit==1.2.3rc1
  - pdd --source=$(pwd) --file=/dev/null
  - est --dir=est --file=/dev/null
  - aibolit check --folder=src/main
  - mvn clean install -Pqulice --errors --batch-mode
addons:
  apt:
    packages:
    - libmagic1
    - libmagic-dev
before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - gem install pdd -v 0.20.5
  - gem install est -v 0.3.4
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8
