language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    sources:
      - deadsnakes
    packages:
    - python3.7
    - libmagic1
    - libmagic-dev
script:
  - set -e
  - pip3 install aibolit==1.2.3rc1
  - pdd --source=$(pwd) --file=/dev/null
  - est --dir=est --file=/dev/null
  - aibolit check --folder=src/main
  - mvn clean install -Pqulice --errors --batch-mode
before_install:
  - sudo apt-get update
  - sudo apt purge python2.7-minimal
  - sudo apt-get install python3 python3-pip python3-setuptools
  - rvm install 2.6.0
  - rvm use 2.6.0
  - python3 --version
  - pip3 --version
install:
  - gem install pdd -v 0.20.5
  - gem install est -v 0.3.4
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8
