# SPDX-FileCopyrightText: Copyright (c) 2013-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitignore",
    ".pdd",
    "**.json",
    "**.md",
    "**.png",
    "**.svg",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CNAME",
    "CNAME",
    "README.md",
    "renovate.json",
    "src/it/saxon/src/test/resources/META-INF/services/javax.xml.transform.TransformerFactory",
    "src/it/xerces/src/test/resources/META-INF/services/javax.xml.parsers.DocumentBuilderFactory",
    "src/it/xerces/src/test/resources/META-INF/services/javax.xml.transform.TransformerFactory",
    "src/it/xerces/src/test/resources/META-INF/services/javax.xml.xpath.XPathFactory",
    "src/site/resources/CNAME",
    "src/site/resources/favicon.ico",
    "src/site/resources/logo-256x256.png",
    "src/site/resources/logo-64x64.png",
    "src/site/resources/logo.png",
    "src/www.xembly.org/logo.png",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2013-2026 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
